# Generated by Django 6.0.1 on 2026-01-24 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(default='#', max_length=255)),
                ('url_image', models.URLField()),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('place', models.CharField(default='Kalemie', max_length=255)),
                ('places_event', models.IntegerField(default=50)),
                ('publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evenement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkGroupDigitalNodus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_names', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('whatsapp_number', models.CharField(max_length=15, unique=True)),
                ('profession', models.CharField()),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')])),
                ('institution', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membre',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpenSourceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projets open source',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialProofComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField()),
                ('fonction', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publish', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Avis Social',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url_site', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Soutient',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_names', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('whatsapp_number', models.CharField(max_length=15, unique=True)),
                ('profession', models.CharField()),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')])),
                ('institution', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='landing.event')),
            ],
            options={
                'verbose_name': 'Reservation',
                'ordering': ['created_at'],
            },
        ),
    ]
